# Generated by Django 3.2 on 2021-05-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0004_auto_20210501_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='times_played',
            field=models.IntegerField(default=0),
        ),
    ]
